//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Sooda.SoodaObjectsAssembly(typeof(VMF.BusinessObjects._DatabaseSchema))]

namespace VMF.BusinessObjects {
  using System;
  using System.Collections;
  using System.Diagnostics;
  using System.Data;
  using Sooda;
  using VMFBusinessObjectsStubs = VMF.BusinessObjects.Stubs;
  
  public class ObjectClassList : Sooda.ObjectMapper.SoodaObjectCollectionWrapperGeneric<ObjectClass> {
    public ObjectClassList() {
    }
    public ObjectClassList(ISoodaObjectList list) : 
        base(list) {
    }
    public ObjectClassList Sort(IComparer comparer) {
      return new ObjectClassList(base.Sort2(comparer));
    }
    public ObjectClassList Sort(string sortOrder) {
      return new ObjectClassList(base.Sort2(sortOrder));
    }
    public ObjectClassList Sort(Sooda.QL.SoqlExpression sortExpression) {
      return new ObjectClassList(base.Sort2(sortExpression));
    }
    public ObjectClassList Sort(Sooda.QL.SoqlExpression sortExpression, Sooda.SortOrder sortOrder) {
      return new ObjectClassList(base.Sort2(sortExpression, sortOrder));
    }
    public ObjectClassList SelectFirst(int count) {
      return new ObjectClassList(base.SelectFirst2(count));
    }
    public ObjectClassList SelectLast(int count) {
      return new ObjectClassList(base.SelectLast2(count));
    }
    public ObjectClassList SelectRange(int _from, int _to) {
      return new ObjectClassList(base.SelectRange2(_from, _to));
    }
    public ObjectClassList Filter(SoodaObjectFilter f) {
      return new ObjectClassList(base.Filter2(f));
    }
    public ObjectClassList Filter(Sooda.QL.SoqlBooleanExpression sortExpression) {
      return new ObjectClassList(base.Filter2(sortExpression));
    }
    public ObjectClassList Filter(SoodaWhereClause whereClause) {
      return new ObjectClassList(base.Filter2(whereClause));
    }
    public ObjectClassList GetSnapshot() {
      return new ObjectClassList(base.GetSnapshot2());
    }
  }
  public class KeyGenList : Sooda.ObjectMapper.SoodaObjectCollectionWrapperGeneric<KeyGen> {
    public KeyGenList() {
    }
    public KeyGenList(ISoodaObjectList list) : 
        base(list) {
    }
    public KeyGenList Sort(IComparer comparer) {
      return new KeyGenList(base.Sort2(comparer));
    }
    public KeyGenList Sort(string sortOrder) {
      return new KeyGenList(base.Sort2(sortOrder));
    }
    public KeyGenList Sort(Sooda.QL.SoqlExpression sortExpression) {
      return new KeyGenList(base.Sort2(sortExpression));
    }
    public KeyGenList Sort(Sooda.QL.SoqlExpression sortExpression, Sooda.SortOrder sortOrder) {
      return new KeyGenList(base.Sort2(sortExpression, sortOrder));
    }
    public KeyGenList SelectFirst(int count) {
      return new KeyGenList(base.SelectFirst2(count));
    }
    public KeyGenList SelectLast(int count) {
      return new KeyGenList(base.SelectLast2(count));
    }
    public KeyGenList SelectRange(int _from, int _to) {
      return new KeyGenList(base.SelectRange2(_from, _to));
    }
    public KeyGenList Filter(SoodaObjectFilter f) {
      return new KeyGenList(base.Filter2(f));
    }
    public KeyGenList Filter(Sooda.QL.SoqlBooleanExpression sortExpression) {
      return new KeyGenList(base.Filter2(sortExpression));
    }
    public KeyGenList Filter(SoodaWhereClause whereClause) {
      return new KeyGenList(base.Filter2(whereClause));
    }
    public KeyGenList GetSnapshot() {
      return new KeyGenList(base.GetSnapshot2());
    }
  }
}
namespace VMF.BusinessObjects.Stubs {
  using System;
  using System.Collections;
  using System.Diagnostics;
  using System.Data;
  using Sooda;
  using Sooda.ObjectMapper;
  using VMFBusinessObjects = VMF.BusinessObjects;
  
  public class ObjectClass_Values : Sooda.SoodaObjectReflectionCachingFieldValues {
    public int Id;
    public string Name;
    public ObjectClass_Values(Sooda.SoodaObjectReflectionCachingFieldValues other) : 
        base(other) {
    }
    public ObjectClass_Values(string[] fieldNames) : 
        base(fieldNames) {
    }
    public override Sooda.SoodaObjectFieldValues Clone() {
      return new ObjectClass_Values(this);
    }
  }
  public abstract class ObjectClass_Stub : VMF.BusinessObjects.Common.BaseObject {
    private static IPrimaryKeyGenerator keyGenerator = new Sooda.ObjectMapper.KeyGenerators.TableBasedGenerator("ObjectClass", VMFBusinessObjects._DatabaseSchema.GetSchema().GetDataSourceInfo("default"));
    public ObjectClass_Stub(SoodaTransaction tran) : 
        base(tran) {
      this.InitNewObject();
    }
    public ObjectClass_Stub(SoodaConstructor c) : 
        base(c) {
    }
    public static System.Linq.IQueryable<ObjectClass> AllQuery {
      get {
        return Linq(SoodaSnapshotOptions.NoWriteObjects);
      }
    }
    public int Id {
      get {
        return ((int)(this.GetPrimaryKeyValue()));
      }
      set {
        this.SetPrimaryKeyValue(value);
      }
    }
    public string Name {
      get {
        return this.GetObjectClassFieldValuesForRead(0).Name;
      }
      set {
        Sooda.ObjectMapper.SoodaObjectImpl.SetPlainFieldValue(this, 0, "Name", 1, Sooda.SoodaNullable.Box(value), new Sooda.SoodaFieldUpdateDelegate(this.BeforeFieldUpdate_Name), new Sooda.SoodaFieldUpdateDelegate(this.AfterFieldUpdate_Name));
      }
    }
    private ObjectClass_Values GetObjectClassFieldValuesForRead(int requiredTable) {
      return ((ObjectClass_Values)(Sooda.ObjectMapper.SoodaObjectImpl.GetFieldValuesForRead(this, requiredTable)));
    }
    protected override SoodaObjectFieldValues InitFieldValues(int fieldCount, string[] fieldNames) {
      return new ObjectClass_Values(fieldNames);
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public override Sooda.Schema.ClassInfo GetClassInfo() {
      return ObjectClass_Factory.TheClassInfo;
    }
    protected override Sooda.ObjectMapper.SoodaFieldHandler GetFieldHandler(int ordinal) {
      return ObjectClass_Factory.InternalGetFieldHandler(ordinal);
    }
    public static IPrimaryKeyGenerator GetKeyGenerator() {
      return keyGenerator;
    }
    protected override void InitNewObject() {
      if (GetTransaction().IsKeyGeneratorDisabled("ObjectClass")) {
        return;
      }
      this.SetPrimaryKeyValue(GetKeyGenerator().GetNextKeyValue());
    }
    private static ObjectClassList DoGetList(SoodaTransaction tran, SoodaWhereClause whereClause, SoodaOrderBy orderByClause, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return new ObjectClassList(new Sooda.ObjectMapper.SoodaObjectListSnapshot(tran, whereClause, orderByClause, startIdx, pageCount, options, ObjectClass_Factory.TheClassInfo));
    }
    public static ObjectClass LoadSingleObject(Sooda.QL.SoqlBooleanExpression filterExpression) {
      return ((ObjectClass)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectBE(filterExpression, DoGetList(SoodaTransaction.ActiveTransaction, new Sooda.SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static ObjectClass LoadSingleObject(Sooda.SoodaWhereClause where) {
      return ((ObjectClass)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectWC(where, DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static ObjectClass LoadSingleObject(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression) {
      return ((ObjectClass)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectBE(filterExpression, DoGetList(tran, new Sooda.SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static ObjectClass LoadSingleObject(SoodaTransaction tran, Sooda.SoodaWhereClause where) {
      return ((ObjectClass)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectWC(where, DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static ObjectClassList GetAllObjects() {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause("1=1"), SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetAllObjects(SoodaTransaction transaction) {
      return DoGetList(transaction, null, SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaOrderBy orderBy) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, -1, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy) {
      return DoGetList(tran, where, orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, orderBy, 0, -1, options);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, topCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, int topCount) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(tran, where, orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, orderBy, 0, topCount, options);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, int startIdx, int pageCount) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(tran, where, orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, orderBy, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, -1, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, -1, options);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int topCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, options);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static ObjectClassList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, options);
    }
    public static ObjectClass Load(int id) {
      return Load(SoodaTransaction.ActiveTransaction, id);
    }
    public static ObjectClass Load(SoodaTransaction tran, int id) {
      ObjectClass retVal = ObjectClass_Stub.GetRef(tran, id);
      Sooda.ObjectMapper.SoodaObjectImpl.LoadAllData(retVal);
      return retVal;
    }
    public static ObjectClass GetRef(int id) {
      return GetRef(SoodaTransaction.ActiveTransaction, id);
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public static ObjectClass TryGet(int id) {
      return TryGet(SoodaTransaction.ActiveTransaction, id);
    }
    public static ObjectClass GetRef(SoodaTransaction tran, int id) {
      return ((ObjectClass)(Sooda.SoodaObject.GetRefHelper(tran, ObjectClass_Factory.TheFactory, id)));
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public static ObjectClass TryGet(SoodaTransaction tran, int id) {
      return ((ObjectClass)(tran.FindObjectWithKey("ObjectClass", id, typeof(ObjectClass))));
    }
    public static ObjectClass GetRef(SoodaTransaction tran, SoodaTuple tuple) {
      return ((ObjectClass)(Sooda.SoodaObject.GetRefHelper(tran, ObjectClass_Factory.TheFactory, tuple)));
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public static ObjectClass TryGet(SoodaTransaction tran, SoodaTuple tuple) {
      return ((ObjectClass)(tran.FindObjectWithKey("ObjectClass", tuple, typeof(ObjectClass))));
    }
    public static System.Linq.IQueryable<ObjectClass> Linq() {
      return Linq(SoodaTransaction.ActiveTransaction, SoodaSnapshotOptions.Default);
    }
    public static System.Linq.IQueryable<ObjectClass> Linq(SoodaSnapshotOptions options) {
      return Linq(SoodaTransaction.ActiveTransaction, options);
    }
    public static System.Linq.IQueryable<ObjectClass> Linq(SoodaTransaction tran, SoodaSnapshotOptions options) {
      return new Sooda.Linq.SoodaQuerySource<ObjectClass>(tran, ObjectClass_Factory.TheClassInfo, options);
    }
    protected virtual void BeforeFieldUpdate_Name(object oldValue, object newValue) {
      this.BeforeFieldUpdate("Name", oldValue, newValue);
    }
    protected virtual void AfterFieldUpdate_Name(object oldValue, object newValue) {
      this.AfterFieldUpdate("Name", oldValue, newValue);
    }
  }
  public class KeyGen_Values : Sooda.SoodaObjectReflectionCachingFieldValues {
    public string KeyName;
    public int KeyValue;
    public KeyGen_Values(Sooda.SoodaObjectReflectionCachingFieldValues other) : 
        base(other) {
    }
    public KeyGen_Values(string[] fieldNames) : 
        base(fieldNames) {
    }
    public override Sooda.SoodaObjectFieldValues Clone() {
      return new KeyGen_Values(this);
    }
  }
  public abstract class KeyGen_Stub : VMF.BusinessObjects.Common.BaseObject {
    public KeyGen_Stub(SoodaTransaction tran) : 
        base(tran) {
      this.InitNewObject();
    }
    public KeyGen_Stub(SoodaConstructor c) : 
        base(c) {
    }
    public static System.Linq.IQueryable<KeyGen> AllQuery {
      get {
        return Linq(SoodaSnapshotOptions.NoWriteObjects);
      }
    }
    [Sooda.SoodaFieldSizeAttribute(64)]
    public string KeyName {
      get {
        return ((string)(this.GetPrimaryKeyValue()));
      }
      set {
        this.SetPrimaryKeyValue(value);
      }
    }
    public int KeyValue {
      get {
        return this.GetKeyGenFieldValuesForRead(0).KeyValue;
      }
      set {
        Sooda.ObjectMapper.SoodaObjectImpl.SetPlainFieldValue(this, 0, "KeyValue", 1, Sooda.SoodaNullable.Box(value), new Sooda.SoodaFieldUpdateDelegate(this.BeforeFieldUpdate_KeyValue), new Sooda.SoodaFieldUpdateDelegate(this.AfterFieldUpdate_KeyValue));
      }
    }
    private KeyGen_Values GetKeyGenFieldValuesForRead(int requiredTable) {
      return ((KeyGen_Values)(Sooda.ObjectMapper.SoodaObjectImpl.GetFieldValuesForRead(this, requiredTable)));
    }
    protected override SoodaObjectFieldValues InitFieldValues(int fieldCount, string[] fieldNames) {
      return new KeyGen_Values(fieldNames);
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public override Sooda.Schema.ClassInfo GetClassInfo() {
      return KeyGen_Factory.TheClassInfo;
    }
    protected override Sooda.ObjectMapper.SoodaFieldHandler GetFieldHandler(int ordinal) {
      return KeyGen_Factory.InternalGetFieldHandler(ordinal);
    }
    protected override void InitNewObject() {
      this.RegisterObjectInTransaction();
    }
    private static KeyGenList DoGetList(SoodaTransaction tran, SoodaWhereClause whereClause, SoodaOrderBy orderByClause, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return new KeyGenList(new Sooda.ObjectMapper.SoodaObjectListSnapshot(tran, whereClause, orderByClause, startIdx, pageCount, options, KeyGen_Factory.TheClassInfo));
    }
    public static KeyGen LoadSingleObject(Sooda.QL.SoqlBooleanExpression filterExpression) {
      return ((KeyGen)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectBE(filterExpression, DoGetList(SoodaTransaction.ActiveTransaction, new Sooda.SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static KeyGen LoadSingleObject(Sooda.SoodaWhereClause where) {
      return ((KeyGen)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectWC(where, DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static KeyGen LoadSingleObject(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression) {
      return ((KeyGen)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectBE(filterExpression, DoGetList(tran, new Sooda.SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static KeyGen LoadSingleObject(SoodaTransaction tran, Sooda.SoodaWhereClause where) {
      return ((KeyGen)(Sooda.ObjectMapper.SoodaObjectImpl.SelectSingleObjectWC(where, DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, 2, SoodaSnapshotOptions.Default))));
    }
    public static KeyGenList GetAllObjects() {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause("1=1"), SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetAllObjects(SoodaTransaction transaction) {
      return DoGetList(transaction, null, SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaOrderBy orderBy) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, -1, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy) {
      return DoGetList(tran, where, orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, orderBy, 0, -1, options);
    }
    public static KeyGenList GetList(SoodaWhereClause where, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, 0, topCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, int topCount) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(tran, where, orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, orderBy, 0, topCount, options);
    }
    public static KeyGenList GetList(SoodaWhereClause where, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, where, orderBy, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, int startIdx, int pageCount) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(tran, where, orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, SoodaWhereClause where, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, where, orderBy, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, -1, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, -1, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, -1, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, -1, options);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int topCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, 0, topCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int topCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, 0, topCount, options);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(SoodaTransaction.ActiveTransaction, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), SoodaOrderBy.Unsorted, startIdx, pageCount, options);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, SoodaSnapshotOptions.Default);
    }
    public static KeyGenList GetList(SoodaTransaction tran, Sooda.QL.SoqlBooleanExpression filterExpression, SoodaOrderBy orderBy, int startIdx, int pageCount, SoodaSnapshotOptions options) {
      return DoGetList(tran, new SoodaWhereClause(filterExpression), orderBy, startIdx, pageCount, options);
    }
    public static KeyGen Load(string keyName) {
      return Load(SoodaTransaction.ActiveTransaction, keyName);
    }
    public static KeyGen Load(SoodaTransaction tran, string keyName) {
      KeyGen retVal = KeyGen_Stub.GetRef(tran, keyName);
      Sooda.ObjectMapper.SoodaObjectImpl.LoadAllData(retVal);
      return retVal;
    }
    public static KeyGen GetRef(string keyName) {
      return GetRef(SoodaTransaction.ActiveTransaction, keyName);
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public static KeyGen TryGet(string keyName) {
      return TryGet(SoodaTransaction.ActiveTransaction, keyName);
    }
    public static KeyGen GetRef(SoodaTransaction tran, string keyName) {
      return ((KeyGen)(Sooda.SoodaObject.GetRefHelper(tran, KeyGen_Factory.TheFactory, keyName)));
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public static KeyGen TryGet(SoodaTransaction tran, string keyName) {
      return ((KeyGen)(tran.FindObjectWithKey("KeyGen", keyName, typeof(KeyGen))));
    }
    public static KeyGen GetRef(SoodaTransaction tran, SoodaTuple tuple) {
      return ((KeyGen)(Sooda.SoodaObject.GetRefHelper(tran, KeyGen_Factory.TheFactory, tuple)));
    }
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public static KeyGen TryGet(SoodaTransaction tran, SoodaTuple tuple) {
      return ((KeyGen)(tran.FindObjectWithKey("KeyGen", tuple, typeof(KeyGen))));
    }
    public static System.Linq.IQueryable<KeyGen> Linq() {
      return Linq(SoodaTransaction.ActiveTransaction, SoodaSnapshotOptions.Default);
    }
    public static System.Linq.IQueryable<KeyGen> Linq(SoodaSnapshotOptions options) {
      return Linq(SoodaTransaction.ActiveTransaction, options);
    }
    public static System.Linq.IQueryable<KeyGen> Linq(SoodaTransaction tran, SoodaSnapshotOptions options) {
      return new Sooda.Linq.SoodaQuerySource<KeyGen>(tran, KeyGen_Factory.TheClassInfo, options);
    }
    protected virtual void BeforeFieldUpdate_KeyValue(object oldValue, object newValue) {
      this.BeforeFieldUpdate("KeyValue", oldValue, newValue);
    }
    protected virtual void AfterFieldUpdate_KeyValue(object oldValue, object newValue) {
      this.AfterFieldUpdate("KeyValue", oldValue, newValue);
    }
  }
  [SoodaObjectFactoryAttribute("ObjectClass", typeof(ObjectClass))]
  public class ObjectClass_Factory : object, ISoodaObjectFactory {
    private static SoodaFieldHandler _primaryKeyFieldHandler = new Sooda.ObjectMapper.FieldHandlers.Int32FieldHandler(false);
    private static ObjectClass_Factory _theFactory = new ObjectClass_Factory();
    private static Sooda.Schema.ClassInfo _theClassInfo = VMF.BusinessObjects._DatabaseSchema.GetSchema().FindClassByName("ObjectClass");
    private static Type _theType = typeof(ObjectClass);
    private ObjectClass_Factory() {
    }
    public static ObjectClass_Factory TheFactory {
      get {
        return _theFactory;
      }
    }
    public virtual Type TheType {
      get {
        return _theType;
      }
    }
    public static Sooda.Schema.ClassInfo TheClassInfo {
      get {
        return _theClassInfo;
      }
    }
    public virtual SoodaObject GetRef(SoodaTransaction tran, object keyValue) {
      return ObjectClass_Stub.GetRef(tran, ((int)(keyValue)));
    }
    public virtual SoodaObject TryGet(SoodaTransaction tran, object keyValue) {
      return ObjectClass_Stub.TryGet(tran, ((int)(keyValue)));
    }
    public virtual System.Collections.IList GetList(SoodaTransaction tran, SoodaWhereClause whereClause, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return new Sooda.ObjectMapper.SoodaObjectListSnapshot(tran, whereClause, orderBy, 0, -1, options, TheClassInfo);
    }
    public virtual Sooda.Schema.ClassInfo GetClassInfo() {
      return TheClassInfo;
    }
    public virtual Sooda.ObjectMapper.SoodaFieldHandler GetPrimaryKeyFieldHandler() {
      return _primaryKeyFieldHandler;
    }
    public virtual Sooda.ObjectMapper.SoodaFieldHandler GetFieldHandler(int ordinal) {
      return InternalGetFieldHandler(ordinal);
    }
    internal static Sooda.ObjectMapper.SoodaFieldHandler InternalGetFieldHandler(int ordinal) {
      return _theClassInfo.UnifiedFields[ordinal].GetFieldHandler();
    }
    public virtual SoodaObject CreateNew(SoodaTransaction tran) {
      return new ObjectClass(tran);
    }
    public virtual SoodaObject GetRawObject(SoodaTransaction tran) {
      ObjectClass retVal = new ObjectClass(SoodaConstructor.Constructor);
      retVal.InitRawObject(tran);
      return retVal;
    }
  }
  [SoodaObjectFactoryAttribute("KeyGen", typeof(KeyGen))]
  public class KeyGen_Factory : object, ISoodaObjectFactory {
    private static SoodaFieldHandler _primaryKeyFieldHandler = new Sooda.ObjectMapper.FieldHandlers.StringFieldHandler(false);
    private static KeyGen_Factory _theFactory = new KeyGen_Factory();
    private static Sooda.Schema.ClassInfo _theClassInfo = VMF.BusinessObjects._DatabaseSchema.GetSchema().FindClassByName("KeyGen");
    private static Type _theType = typeof(KeyGen);
    private KeyGen_Factory() {
    }
    public static KeyGen_Factory TheFactory {
      get {
        return _theFactory;
      }
    }
    public virtual Type TheType {
      get {
        return _theType;
      }
    }
    public static Sooda.Schema.ClassInfo TheClassInfo {
      get {
        return _theClassInfo;
      }
    }
    public virtual SoodaObject GetRef(SoodaTransaction tran, object keyValue) {
      return KeyGen_Stub.GetRef(tran, ((string)(keyValue)));
    }
    public virtual SoodaObject TryGet(SoodaTransaction tran, object keyValue) {
      return KeyGen_Stub.TryGet(tran, ((string)(keyValue)));
    }
    public virtual System.Collections.IList GetList(SoodaTransaction tran, SoodaWhereClause whereClause, SoodaOrderBy orderBy, SoodaSnapshotOptions options) {
      return new Sooda.ObjectMapper.SoodaObjectListSnapshot(tran, whereClause, orderBy, 0, -1, options, TheClassInfo);
    }
    public virtual Sooda.Schema.ClassInfo GetClassInfo() {
      return TheClassInfo;
    }
    public virtual Sooda.ObjectMapper.SoodaFieldHandler GetPrimaryKeyFieldHandler() {
      return _primaryKeyFieldHandler;
    }
    public virtual Sooda.ObjectMapper.SoodaFieldHandler GetFieldHandler(int ordinal) {
      return InternalGetFieldHandler(ordinal);
    }
    internal static Sooda.ObjectMapper.SoodaFieldHandler InternalGetFieldHandler(int ordinal) {
      return _theClassInfo.UnifiedFields[ordinal].GetFieldHandler();
    }
    public virtual SoodaObject CreateNew(SoodaTransaction tran) {
      return new KeyGen(tran);
    }
    public virtual SoodaObject GetRawObject(SoodaTransaction tran) {
      KeyGen retVal = new KeyGen(SoodaConstructor.Constructor);
      retVal.InitRawObject(tran);
      return retVal;
    }
  }
}
namespace VMF.BusinessObjects {
  using System;
  using System.Collections;
  using System.Diagnostics;
  using System.Data;
  using Sooda;
  using VMFBusinessObjectsStubs = VMF.BusinessObjects.Stubs;
  
  public class _DatabaseSchema : object, Sooda.ObjectMapper.ISoodaSchema {
    private Sooda.ISoodaObjectFactory[] _factories;
    private Sooda.IInterfaceProxyFactory[] _proxies;
    private static Sooda.Schema.SchemaInfo _theSchema;
    static _DatabaseSchema() {
      _theSchema = LoadSchema();
    }
    public _DatabaseSchema() {
      this._factories = new ISoodaObjectFactory[] {
          VMF.BusinessObjects.Stubs.ObjectClass_Factory.TheFactory,
          VMF.BusinessObjects.Stubs.KeyGen_Factory.TheFactory};
      this._proxies = new IInterfaceProxyFactory[0];
    }
    public virtual Sooda.Schema.SchemaInfo Schema {
      get {
        return GetSchema();
      }
    }
    public static Sooda.Schema.SchemaInfo GetSchema() {
      return _theSchema;
    }
    private static Sooda.Schema.SchemaInfo LoadSchema() {
      return Sooda.ObjectMapper.SchemaLoader.GetSchemaFromAssembly(typeof(VMF.BusinessObjects._DatabaseSchema).Assembly);
    }
    public virtual Sooda.ISoodaObjectFactory[] GetFactories() {
      return this._factories;
    }
    public virtual Sooda.IInterfaceProxyFactory[] GetProxies() {
      return this._proxies;
    }
  }
}
